version: "3"

services:
  gin_practice_db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data_gin_practice:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: gostgres
      POSTGRES_PASSWORD: go_pw
      POSTGRES_DB: gin_practice
    ports:
      - "5436:5432"

  gin_practice_db_test:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data_gin_practice_test:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: gostgres
      POSTGRES_PASSWORD: go_pw
      POSTGRES_DB: gin_practice_test
    ports:
      - "5437:5432"

volumes:
  postgres_data_gin_practice: null
  postgres_data_gin_practice_test: null
